packages:
  - packages/core
  - packages/runtime
  - packages/node
allowBuilds:
  '@swc/core': true
  esbuild: true
  msw: false
  nx: false
minimumReleaseAgeExclude:
  - '@softarc/native-federation-runtime@4.1.2'
